[build]
    functions = "netlify/functions"
    publish = "."
  
  [[plugins]]
    package = "@netlify/plugin-functions-install-core"
  
  [[headers]]
    for = "/netlify/functions/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
